create user std1 identified by p123;
grant create session to std1;
create user std2 identified by p123;
grant create session to std2;
create user std3 identified by p123;
grant create session to std3;
create user std4 identified by p123;
grant create session to std4;
create user std5 identified by p123;
grant create session to std5;
create user std6 identified by p123;
grant create session to std6;
create user std7 identified by p123;
grant create session to std7;
create user std8 identified by p123;
grant create session to std8;
create user std9 identified by p123;
grant create session to std9;
create user std10 identified by p123;
grant create session to std10;
create user std11 identified by p123;
grant create session to std11;
create user std12 identified by p123;
grant create session to std12;
create user std13 identified by p123;
grant create session to std13;
create user std14 identified by p123;
grant create session to std14;
create user std15 identified by p123;
grant create session to std15;
create user std16 identified by p123;
grant create session to std16;
create user std17 identified by p123;
grant create session to std17;
create user std18 identified by p123;
grant create session to std18;
create user std19 identified by p123;
grant create session to std19;
create user std20 identified by p123;
grant create session to std20;
create user std21 identified by p123;
grant create session to std21;
create user std22 identified by p123;
grant create session to std22;
create user std23 identified by p123;
grant create session to std23;
create user std24 identified by p123;
grant create session to std24;
create user std25 identified by p123;
grant create session to std25;
create user std26 identified by p123;
grant create session to std26;
create user std27 identified by p123;
grant create session to std27;
create user std28 identified by p123;
grant create session to std28;
create user std29 identified by p123;
grant create session to std29;
create user std30 identified by p123;
grant create session to std30;
create user std31 identified by p123;
grant create session to std31;
create user std32 identified by p123;
grant create session to std32;
create user std33 identified by p123;
grant create session to std33;
create user std34 identified by p123;
grant create session to std34;
create user std35 identified by p123;
grant create session to std35;
create user std36 identified by p123;
grant create session to std36;
create user std37 identified by p123;
grant create session to std37;
create user std38 identified by p123;
grant create session to std38;
create user std39 identified by p123;
grant create session to std39;
create user std40 identified by p123;
grant create session to std40;
create user std41 identified by p123;
grant create session to std41;
create user std42 identified by p123;
grant create session to std42;
create user std43 identified by p123;
grant create session to std43;
create user std44 identified by p123;
grant create session to std44;
create user std45 identified by p123;
grant create session to std45;
create user std46 identified by p123;
grant create session to std46;
create user std47 identified by p123;
grant create session to std47;
create user std48 identified by p123;
grant create session to std48;
create user std49 identified by p123;
grant create session to std49;
create user std50 identified by p123;
grant create session to std50;
create user std51 identified by p123;
grant create session to std51;
create user std52 identified by p123;
grant create session to std52;
create user std53 identified by p123;
grant create session to std53;
create user std54 identified by p123;
grant create session to std54;
create user std55 identified by p123;
grant create session to std55;
create user std56 identified by p123;
grant create session to std56;
create user std57 identified by p123;
grant create session to std57;
create user std58 identified by p123;
grant create session to std58;
create user std59 identified by p123;
grant create session to std59;
create user std60 identified by p123;
grant create session to std60;

create user tc1 identified by p123;
grant create session to tc1;
create user tc2 identified by p123;
grant create session to tc2;
create user tc3 identified by p123;
grant create session to tc3;
create user tc4 identified by p123;
grant create session to tc4;
create user tc5 identified by p123;
grant create session to tc5;
create user tc6 identified by p123;
grant create session to tc6;
create user tc7 identified by p123;
grant create session to tc7;
create user tc8 identified by p123;
grant create session to tc8;
create user tc9 identified by p123;
grant create session to tc9;
create user tc10 identified by p123;
grant create session to tc10;
create user tc11 identified by p123;
grant create session to tc11;
create user tc12 identified by p123;
grant create session to tc12;
create user tc13 identified by p123;
grant create session to tc13;
create user tc14 identified by p123;
grant create session to tc14;
create user tc15 identified by p123;
grant create session to tc15;
create user tc16 identified by p123;
grant create session to tc16;
create user tc17 identified by p123;
grant create session to tc17;
create user tc18 identified by p123;
grant create session to tc18;
create user tc19 identified by p123;
grant create session to tc19;
create user tc20 identified by p123;
grant create session to tc20;

create user pr1 identified by p123;
grant create session to pr1;
create user pr2 identified by p123;
grant create session to pr2;
create user pr3 identified by p123;
grant create session to pr3;
create user pr4 identified by p123;
grant create session to pr4;
create user pr5 identified by p123;
grant create session to pr5;
create user pr6 identified by p123;
grant create session to pr6;
create user pr7 identified by p123;
grant create session to pr7;
create user pr8 identified by p123;
grant create session to pr8;
create user pr9 identified by p123;
grant create session to pr9;
create user pr10 identified by p123;
grant create session to pr10;
create user pr11 identified by p123;
grant create session to pr11;
create user pr12 identified by p123;
grant create session to pr12;
create user pr13 identified by p123;
grant create session to pr13;
create user pr14 identified by p123;
grant create session to pr14;
create user pr15 identified by p123;
grant create session to pr15;
create user pr16 identified by p123;
grant create session to pr16;
create user pr17 identified by p123;
grant create session to pr17;
create user pr18 identified by p123;
grant create session to pr18;
create user pr19 identified by p123;
grant create session to pr19;
create user pr20 identified by p123;
grant create session to pr20;
create user pr21 identified by p123;
grant create session to pr21;
create user pr22 identified by p123;
grant create session to pr22;
create user pr23 identified by p123;
grant create session to pr23;
create user pr24 identified by p123;
grant create session to pr24;
create user pr25 identified by p123;
grant create session to pr25;
create user pr26 identified by p123;
grant create session to pr26;
create user pr27 identified by p123;
grant create session to pr27;
create user pr28 identified by p123;
grant create session to pr28;
create user pr29 identified by p123;
grant create session to pr29;
create user pr30 identified by p123;
grant create session to pr30;
create user pr31 identified by p123;
grant create session to pr31;
create user pr32 identified by p123;
grant create session to pr32;
create user pr33 identified by p123;
grant create session to pr33;
create user pr34 identified by p123;
grant create session to pr34;
create user pr35 identified by p123;
grant create session to pr35;
create user pr36 identified by p123;
grant create session to pr36;
create user pr37 identified by p123;
grant create session to pr37;
create user pr38 identified by p123;
grant create session to pr38;
create user pr39 identified by p123;
grant create session to pr39;
create user pr40 identified by p123;
grant create session to pr40;
