-- APPLY POLICY
--CONN sec_admin/secadmin;
--
--BEGIN
--sa_policy_admin.apply_table_policy
--    (policy_name => 'MANAGE_SCORE',
--    schema_name => 'ATV',
--    table_name => 'COURSE_SCORE',
--    table_options => 'NO_CONTROL');
--END;
--/

-- CHECK IF OLS column has been added to table
-- CONN atv/atv;
-- DESCRIBE course_score;

-----------------------UPDATE data labels - COMMIT------------------------------------
BEGIN
    ASSIGN_DATA_LABEL(1,1);
    ASSIGN_DATA_LABEL(2,2);
    ASSIGN_DATA_LABEL(3,3);
    ASSIGN_DATA_LABEL(4,4);
    ASSIGN_DATA_LABEL(5,5);
    ASSIGN_DATA_LABEL(6,6);
    ASSIGN_DATA_LABEL(7,7);
    ASSIGN_DATA_LABEL(8,8);
    ASSIGN_DATA_LABEL(9,9);
    ASSIGN_DATA_LABEL(10,10);
    ASSIGN_DATA_LABEL(11,11);
    ASSIGN_DATA_LABEL(12,12);
    ASSIGN_DATA_LABEL(13,13);
    ASSIGN_DATA_LABEL(14,14);
    ASSIGN_DATA_LABEL(15,15);
    ASSIGN_DATA_LABEL(16,16);
    ASSIGN_DATA_LABEL(17,17);
    ASSIGN_DATA_LABEL(18,18);
    ASSIGN_DATA_LABEL(19,19);
    ASSIGN_DATA_LABEL(20,20);
    ASSIGN_DATA_LABEL(21,21);
    ASSIGN_DATA_LABEL(22,22);
    ASSIGN_DATA_LABEL(23,23);
    ASSIGN_DATA_LABEL(24,24);
    ASSIGN_DATA_LABEL(25,25);
    ASSIGN_DATA_LABEL(26,26);
    ASSIGN_DATA_LABEL(27,27);
    ASSIGN_DATA_LABEL(28,28);
    ASSIGN_DATA_LABEL(29,29);
    ASSIGN_DATA_LABEL(30,30);
    ASSIGN_DATA_LABEL(31,31);
    ASSIGN_DATA_LABEL(32,32);
    ASSIGN_DATA_LABEL(33,33);
    ASSIGN_DATA_LABEL(34,34);
    ASSIGN_DATA_LABEL(35,35);
    ASSIGN_DATA_LABEL(36,36);
    ASSIGN_DATA_LABEL(37,37);
    ASSIGN_DATA_LABEL(38,38);
    ASSIGN_DATA_LABEL(39,39);
    ASSIGN_DATA_LABEL(40,40);
    ASSIGN_DATA_LABEL(41,41);
    ASSIGN_DATA_LABEL(42,42);
    ASSIGN_DATA_LABEL(43,43);
    ASSIGN_DATA_LABEL(44,44);
    ASSIGN_DATA_LABEL(45,45);
    ASSIGN_DATA_LABEL(1,46);
    ASSIGN_DATA_LABEL(2,47);
    ASSIGN_DATA_LABEL(3,48);
    ASSIGN_DATA_LABEL(4,49);
    ASSIGN_DATA_LABEL(5,50);
    ASSIGN_DATA_LABEL(6,51);
    ASSIGN_DATA_LABEL(7,52);
    ASSIGN_DATA_LABEL(8,53);
    ASSIGN_DATA_LABEL(9,54);
    ASSIGN_DATA_LABEL(10,55);
    ASSIGN_DATA_LABEL(11,56);
    ASSIGN_DATA_LABEL(12,57);
    ASSIGN_DATA_LABEL(13,58);
    ASSIGN_DATA_LABEL(14,59);
    ASSIGN_DATA_LABEL(15,60);
    ASSIGN_DATA_LABEL(16,1);
    ASSIGN_DATA_LABEL(17,2);
    ASSIGN_DATA_LABEL(18,3);
    ASSIGN_DATA_LABEL(19,4);
    ASSIGN_DATA_LABEL(20,5);
    ASSIGN_DATA_LABEL(21,6);
    ASSIGN_DATA_LABEL(22,7);
    ASSIGN_DATA_LABEL(23,8);
    ASSIGN_DATA_LABEL(24,9);
    ASSIGN_DATA_LABEL(25,10);
    ASSIGN_DATA_LABEL(26,11);
    ASSIGN_DATA_LABEL(27,12);
    ASSIGN_DATA_LABEL(28,13);
    ASSIGN_DATA_LABEL(29,14);
    ASSIGN_DATA_LABEL(30,15);
    ASSIGN_DATA_LABEL(31,16);
    ASSIGN_DATA_LABEL(32,17);
    ASSIGN_DATA_LABEL(33,18);
    ASSIGN_DATA_LABEL(34,19);
    ASSIGN_DATA_LABEL(35,20);
    ASSIGN_DATA_LABEL(36,21);
    ASSIGN_DATA_LABEL(37,22);
    ASSIGN_DATA_LABEL(38,23);
    ASSIGN_DATA_LABEL(39,24);
    ASSIGN_DATA_LABEL(40,25);
    ASSIGN_DATA_LABEL(41,26);
    ASSIGN_DATA_LABEL(42,27);
    ASSIGN_DATA_LABEL(43,28);
    ASSIGN_DATA_LABEL(44,29);
    ASSIGN_DATA_LABEL(45,30);
    ASSIGN_DATA_LABEL(1,31);
    ASSIGN_DATA_LABEL(2,32);
    ASSIGN_DATA_LABEL(3,33);
    ASSIGN_DATA_LABEL(4,34);
    ASSIGN_DATA_LABEL(5,35);
    ASSIGN_DATA_LABEL(6,36);
    ASSIGN_DATA_LABEL(7,37);
    ASSIGN_DATA_LABEL(8,38);
    ASSIGN_DATA_LABEL(9,39);
    ASSIGN_DATA_LABEL(10,40);
    ASSIGN_DATA_LABEL(11,41);
    ASSIGN_DATA_LABEL(12,42);
    ASSIGN_DATA_LABEL(13,43);
    ASSIGN_DATA_LABEL(14,44);
    ASSIGN_DATA_LABEL(15,45);
    ASSIGN_DATA_LABEL(16,46);
    ASSIGN_DATA_LABEL(17,47);
    ASSIGN_DATA_LABEL(18,48);
    ASSIGN_DATA_LABEL(19,49);
    ASSIGN_DATA_LABEL(20,50);
    ASSIGN_DATA_LABEL(21,51);
    ASSIGN_DATA_LABEL(22,52);
    ASSIGN_DATA_LABEL(23,53);
    ASSIGN_DATA_LABEL(24,54);
    ASSIGN_DATA_LABEL(25,55);
    ASSIGN_DATA_LABEL(26,56);
    ASSIGN_DATA_LABEL(27,57);
    ASSIGN_DATA_LABEL(28,58);
    ASSIGN_DATA_LABEL(29,59);
    ASSIGN_DATA_LABEL(30,60);
    ASSIGN_DATA_LABEL(31,1);
    ASSIGN_DATA_LABEL(32,2);
    ASSIGN_DATA_LABEL(33,3);
    ASSIGN_DATA_LABEL(34,4);
    ASSIGN_DATA_LABEL(35,5);
    ASSIGN_DATA_LABEL(36,6);
    ASSIGN_DATA_LABEL(37,7);
    ASSIGN_DATA_LABEL(38,8);
    ASSIGN_DATA_LABEL(39,9);
    ASSIGN_DATA_LABEL(40,10);
    ASSIGN_DATA_LABEL(41,11);
    ASSIGN_DATA_LABEL(42,12);
    ASSIGN_DATA_LABEL(43,13);
    ASSIGN_DATA_LABEL(44,14);
    ASSIGN_DATA_LABEL(45,15);
    ASSIGN_DATA_LABEL(1,16);
    ASSIGN_DATA_LABEL(2,17);
    ASSIGN_DATA_LABEL(3,18);
    ASSIGN_DATA_LABEL(4,19);
    ASSIGN_DATA_LABEL(5,20);
    ASSIGN_DATA_LABEL(6,21);
    ASSIGN_DATA_LABEL(7,22);
    ASSIGN_DATA_LABEL(8,23);
    ASSIGN_DATA_LABEL(9,24);
    ASSIGN_DATA_LABEL(10,25);
    ASSIGN_DATA_LABEL(11,26);
    ASSIGN_DATA_LABEL(12,27);
    ASSIGN_DATA_LABEL(13,28);
    ASSIGN_DATA_LABEL(14,29);
    ASSIGN_DATA_LABEL(15,30);
    ASSIGN_DATA_LABEL(16,31);
    ASSIGN_DATA_LABEL(17,32);
    ASSIGN_DATA_LABEL(18,33);
    ASSIGN_DATA_LABEL(19,34);
    ASSIGN_DATA_LABEL(20,35);
    ASSIGN_DATA_LABEL(21,36);
    ASSIGN_DATA_LABEL(22,37);
    ASSIGN_DATA_LABEL(23,38);
    ASSIGN_DATA_LABEL(24,39);
    ASSIGN_DATA_LABEL(25,40);
    ASSIGN_DATA_LABEL(26,41);
    ASSIGN_DATA_LABEL(27,42);
    ASSIGN_DATA_LABEL(28,43);
    ASSIGN_DATA_LABEL(29,44);
    ASSIGN_DATA_LABEL(30,45);
    ASSIGN_DATA_LABEL(31,46);
    ASSIGN_DATA_LABEL(32,47);
    ASSIGN_DATA_LABEL(33,48);
    ASSIGN_DATA_LABEL(34,49);
    ASSIGN_DATA_LABEL(35,50);
    ASSIGN_DATA_LABEL(36,51);
    ASSIGN_DATA_LABEL(37,52);
    ASSIGN_DATA_LABEL(38,53);
    ASSIGN_DATA_LABEL(39,54);
    ASSIGN_DATA_LABEL(40,55);
    ASSIGN_DATA_LABEL(41,56);
    ASSIGN_DATA_LABEL(42,57);
    ASSIGN_DATA_LABEL(43,58);
    ASSIGN_DATA_LABEL(44,59);
    ASSIGN_DATA_LABEL(45,60);
    COMMIT;
END;
/


-------------------------- RE-ACTIVATE POLICY -------------------------------------------
BEGIN
    sa_policy_admin.remove_table_policy
        (policy_name => 'MANAGE_SCORE',
        schema_name => 'ATV',
        table_name => 'COURSE_SCORE');
end;
/

--begin
--sa_policy_admin.apply_table_policy
--    (policy_name => 'MANAGE_SCORE',
--    schema_name => 'ATV',
--    table_name => 'COURSE_SCORE',
--    table_options => 'READ_CONTROL,WRITE_CONTROL,CHECK_CONTROL');
--END;
--/

BEGIN
SA_POLICY_ADMIN.APPLY_TABLE_POLICY (
    policy_name => 'MANAGE_SCORE',
    schema_name => 'ATV',
    table_name => 'COURSE_SCORE',
    table_options => 'READ_CONTROL,WRITE_CONTROL,CHECK_CONTROL',
    label_function => 'sec_admin.gen_score_label(:new.COURSE_ID, :new.STUDENT_ID)',
    PREDICATE => NULL);
END;
/